### PR TITLE
Storage Queues Binding: Add b64encoding option for messages

### LINKED ISSUE #2249: bindings.azure.storagequeues don't support encodeBase64 when send message
## Expected Behavior

send message with UTF8 characters (like Chinese) into azure storage queue, and can be processed by Azure Function QueueTrigger.

## Actual Behavior

 Azure Function QueueTrigger report this error:

```log
The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
```

## Steps to Reproduce the Problem

- Create dapr app with output binding (use bindings.azure.storagequeues)
- Send a model with daprClient.InvokeBindingAsync("binding-output-importuser", "create", input);
- Create an Azure Function QueueTrigger with same Azure Storage Account to receive the message from output binding

## Release Note

Dapr runtime: 1.8.4

### PR DESCRIPTION
**Pull request by berndverst**
Signed-off-by: Bernd Verst <4535280+berndverst@users.noreply.github.com>

# Description

Adds base64 encoding option for Service Bus Queues binding
Fixes #2249 

* [x] Code compiles correctly
* [x] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

File: tests/certification/bindings/azure/storagequeues/storagequeue_test.go [hunk 1]
```diff
@@ -312,7 +311,7 @@ func TestAzureStorageQueueForDecode(t *testing.T) {
 		// Declare the expected data.
 		msgs := make([]string, numOfMessages)
 		for i := 0; i < numOfMessages; i++ {
-			msgs[i] = fmt.Sprintf("Message %03d", i)
+			msgs[i] = fmt.Sprintf("Message 新 %03d", i) // the chinese character is part of the test for UTF-8 characters
```
Comment (ItalyPaleAle) [inline tests/certification/bindings/azure/storagequeues/storagequeue_test.go:314]: I normally use emojis 🤷

**Review by ItalyPaleAle — APPROVED** [review]

File: tests/certification/bindings/azure/storagequeues/storagequeue_test.go (hunk 1 above)
Comment (berndverst) [reply tests/certification/bindings/azure/storagequeues/storagequeue_test.go:314]: I used Chinese because the impacted user had issues with Chinese characters. The character I used means "message" :)
