### PR TITLE
Fix #1351 Fail with useful error message when an invalid account name is used

### LINKED ISSUE #1351: Panic on azure blob storage state store
## Expected Behavior

Invalid Azure storage account name does not cause a panic and gives proper error message.

## Actual Behavior

Providing an invalid Azure storage account name to Azure storage state store causes panic.

image

## Steps to Reproduce the Problem

Use azure blob storage state store with an invalid account name

## Release Note

RELEASE NOTE:

### PR DESCRIPTION
**Pull request by Gehhilfe**
# Description

When an invalid account name is provided, the container creation takes longer than 5 seconds init timeout. I did not want to change the timeout behavior of the azblob, therefore I used a DNS lookup to fail fast for non-existing endpoints.

image

## Issue reference

This PR will close: #1351 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests

### CODE REVIEW

File: state/azure/blobstorage/blobstorage.go [hunk 1]
```diff
@@ -91,18 +92,24 @@ func (r *StateStore) Init(metadata state.Metadata) error {
...
-		URL, parseErr := url.Parse(fmt.Sprintf("%s/%s/%s", customEndpoint, meta.accountName, meta.containerName))
-		if parseErr != nil {
-			return parseErr
+		URL, err = url.Parse(fmt.Sprintf("%s/%s/%s", customEndpoint, meta.accountName, meta.containerName))
+		if err != nil {
+			return err
 		}
 		containerURL = azblob.NewContainerURL(*URL, p)
 	} else {
 		URL, _ := url.Parse(fmt.Sprintf("https://%s.blob.%s/%s", meta.accountName, env.StorageEndpointSuffix, meta.containerName))
```
Comment (daixiang0) [inline state/azure/blobstorage/blobstorage.go:104]: If define URL at L95, need to change this line here or revert related changes.

**Comment by daixiang0** [comment]
Also please fix DCO issue.

File: state/azure/blobstorage/blobstorage.go [hunk 2]
```diff
@@ -91,18 +92,24 @@ func (r *StateStore) Init(metadata state.Metadata) error {
...
 	customEndpoint, ok := metadata.Properties[endpointKey]
 	if ok && customEndpoint != "" {
-		URL, parseErr := url.Parse(fmt.Sprintf("%s/%s/%s", customEndpoint, meta.accountName, meta.containerName))
-		if parseErr != nil {
-			return parseErr
+		URL, err = url.Parse(fmt.Sprintf("%s/%s/%s", customEndpoint, meta.accountName, meta.containerName))
+		if err != nil {
+			return err
 		}
 		containerURL = azblob.NewContainerURL(*URL, p)
```
Comment (daixiang0) [inline state/azure/blobstorage/blobstorage.go:102]: Put this line outside if block since it is universal.

File: state/azure/blobstorage/blobstorage.go (hunk 1 above)
Comment (Gehhilfe) [reply state/azure/blobstorage/blobstorage.go]: Updated

File: state/azure/blobstorage/blobstorage.go (hunk 2 above)
Comment (Gehhilfe) [reply state/azure/blobstorage/blobstorage.go]: Pulled out containerURL and error check 
Both code path have now error check

**Review by yaron2 — APPROVED** [review]
