### PR TITLE
Fix Postgres state store hardcoding table name in Delete method

### LINKED ISSUE #2707: Postgres state store: DELETE queries use hardcoded table name
In Dapr 1.10 and master branch, the Postgres state component (stable) has a bug in the `doDelete` method, where DELETE queries use hardcoded table name:

https://github.com/dapr/components-contrib/blob/release-1.10/state/postgresql/postgresdbaccess.go#L326

This means that the Delete method is not usable when the state table has a different name.

### PR DESCRIPTION
**Pull request by ItalyPaleAle**
Fixes #2707

### CODE REVIEW

File: internal/component/postgresql/postgresdbaccess.go [hunk 1]
```diff
@@ -329,7 +329,7 @@ func (p *PostgresDBAccess) doDelete(parentCtx context.Context, db dbquerier, req
 
 	var result pgconn.CommandTag
 	if req.ETag == nil || *req.ETag == "" {
-		result, err = db.Exec(parentCtx, "DELETE FROM state WHERE key = $1", req.Key)
+		result, err = db.Exec(parentCtx, "DELETE FROM "+p.metadata.TableName+" WHERE key = $1", req.Key)
```
Comment (berndverst) [inline internal/component/postgresql/postgresdbaccess.go:332]: Per conversation here, the table name is sanitized so cannot cause a SQL injection. Looks good as a result.

**Review by berndverst — APPROVED** [review]

**Comment by berndverst** [comment]
Should cherry pick this into release-1.10 to include with the next hotfix. I'll do that.
